### ISSUE TITLE
Fetch function doesn't break on non 200 response from API

### ISSUE THREAD

**Issue by bitonio** [akamai/cli-etp#14]
```
root@localhost:~# docker logs root-etp-threat-1
2023-11-02 16:47:00,476 ULS E UlsInputCli - CLI process [8] was found stale - Reason:  "2023-11-02 16:47:00,428 cli-etp MainThread E API call failed with HTTP/400: b'{\n  "type": "https://problems.luna.akamaiapis.net/-/pep-authn/request-error",\n  "title": "Bad request",\n  "status": 400,\n  "detail": "Invalid timestamp",\n  "instance": "https://akab-xxxx-sisx74boynnyo35c.luna.akamaiapis.net/etp-report/v3/configs/xxxx/dns-activities/details?accountSwitchKey=xxxxx",\n  "method": "POST",\n  "serverIp": "x.37.60.14",\n  "clientIp": "x.162.171.151",\n  "requestId": "24425543",\n  "requestTime": "2023-11-02T16:47:00Z"\n}\n'
Traceback (most recent call last):
File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 738, in <module>
main()
File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 669, in main
fetch_events_concurrent(config, out)
File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 376, in fetch_events_concurrent
fetch_event_page(start, end, 1, concurrent_fetch, pool_futures, stats, output)
File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 304, in fetch_event_page
total_records = response_data["pageInfo"]["totalRecords"]
~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'pageInfo'
"
```

**Comment by MikeSchiessl** [comment]
pushing this topic up
